spring.application.name=TravelDiary

google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-url=${GOOGLE_REDIRECT_URL}
google.user-info-url=${GOOGLE_USER_INFO}
google.access-token-url=${GOOGLE_ACCESS_TOKEN_URL}
google.auth-server-url=${GOOGLE_AUTH_SERVER_URL}

spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USERNAME}
spring.datasource.password=${DATA_SOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret.key=${JWT_SECRET_KEY}
jwt.time.expires=${JWT_EXPIRE_TIME}


server.port=8080
server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
